### ISSUE TITLE
peer on ember-styleguide

### ISSUE THREAD

**Issue by mansona** [IgnaceMaes/ember-showdown-shikiji#9]
is there any reason for the peer on ember-styleguide? 🤔 https://github.com/IgnaceMaes/ember-showdown-shikiji/blob/main/ember-showdown-shikiji/package.json#L113

I know this is being used a lot in the ember sites but it doesn't **need** to be. Is it actually depending on something?

**Comment by IgnaceMaes** [comment]
The CSS variables are used for styling purposes: https://github.com/IgnaceMaes/ember-showdown-shikiji/blob/main/ember-showdown-shikiji/src/styles/shikiji.css#L27

This addon expects them to be available, hence the peer.

Any specific reason why? Should this be done differently?

**Comment by mansona** [comment]
so I think this should be separate from ember-styleguide. I just tried to install it into https://github.com/ember-learn/ember-api-docs/pull/902 instead of ember-showdown-prism but ember-api-docs currently depends on a **very** old version of ember-styleguide `"ember-styleguide": "2.6.0-0",`

Does that make sense?

**Comment by IgnaceMaes** [comment]
I see, seems like it's better to just get rid of it then. That's one less dependency to take into account.

I'll have a look later.
